# Generated by Django 6.1 on 2026-09-18 02:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_equipeusf_options_alter_perfilusuario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_responsavel', models.CharField(max_length=11, verbose_name='CPF do Responsável')),
                ('nome_responsavel', models.CharField(max_length=200, verbose_name='Nome do Responsável')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('ponto_referencia', models.CharField(blank=True, max_length=200, verbose_name='Ponto de Referência')),
                ('numero_comodos', models.IntegerField(blank=True, null=True, verbose_name='Nº de Cômodos')),
                ('score_total', models.IntegerField(default=0, verbose_name='Score Total (Pontos)')),
                ('classificacao', models.CharField(choices=[('R0', 'R0 - Sem Risco (0 a 4 pontos)'), ('R1', 'R1 - Risco Baixo (5 a 6 pontos)'), ('R2', 'R2 - Risco Médio (7 a 8 pontos)'), ('R3', 'R3 - Risco Alto (9 ou mais pontos)')], default='R0', max_length=2, verbose_name='Classificação de Risco')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização do Score')),
                ('usf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familias', to='core.usf')),
            ],
            options={
                'verbose_name': 'Score Familiar',
                'verbose_name_plural': 'Scores Familiares',
                'unique_together': {('usf', 'cpf_responsavel')},
            },
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Nome do Logradouro')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logradouros', to='core.usf')),
            ],
            options={
                'verbose_name': 'Logradouro',
                'verbose_name_plural': 'Logradouros',
                'ordering': ['logradouro'],
                'unique_together': {('usf', 'logradouro', 'bairro')},
            },
        ),
        migrations.CreateModel(
            name='SentinelaRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('domicilio', 'Condição do Domicílio (Saneamento, Água, etc)'), ('individual', 'Condição Individual Marcada à Mão (Ex: Desnutrição)'), ('idade', 'Idade Automática (Ex: Menor de 1 ano, Maior de 70)'), ('condicao', 'Condição de Saúde Automática (Ex: Gestante, Acamado)')], max_length=20, verbose_name='Tipo de Sentinela')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Fator de Risco')),
                ('codigo', models.SlugField(unique=True, verbose_name='Código Interno')),
                ('peso', models.IntegerField(default=1, help_text='Quantos pontos este fator soma na família.', verbose_name='Pontos de Risco (Peso)')),
                ('idade_minima', models.IntegerField(blank=True, null=True, verbose_name='Idade Mínima')),
                ('idade_maxima', models.IntegerField(blank=True, null=True, verbose_name='Idade Máxima')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação / Critério Clínico')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('condicao_saude', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.condicaosaude')),
            ],
            options={
                'verbose_name': 'Sentinela de Risco',
                'verbose_name_plural': 'Sentinelas de Risco',
                'ordering': ['tipo', '-peso', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='VinculoLogradouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início do Vínculo')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim do Vínculo')),
                ('numero_inicial', models.IntegerField(blank=True, null=True, verbose_name='Número Inicial')),
                ('numero_final', models.IntegerField(blank=True, null=True, verbose_name='Número Final')),
                ('motivo', models.CharField(blank=True, help_text='Ex: Redivisão de área', max_length=200, verbose_name='Motivo da alteração')),
                ('logradouro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='territorializacao.logradouro')),
                ('micro_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logradouros_vinculados', to='core.microarea')),
            ],
            options={
                'verbose_name': 'Vínculo de Logradouro e Micro-área',
                'verbose_name_plural': 'Vínculos de Logradouros',
            },
        ),
        migrations.CreateModel(
            name='MembroSentinela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territorializacao.familiascore')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentinelas', to='core.paciente')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sentinela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territorializacao.sentinelarisco')),
            ],
            options={
                'unique_together': {('paciente', 'sentinela')},
            },
        ),
        migrations.CreateModel(
            name='FamiliaSentinela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentinelas_domicilio', to='territorializacao.familiascore')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sentinela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territorializacao.sentinelarisco')),
            ],
            options={
                'unique_together': {('familia', 'sentinela')},
            },
        ),
    ]
