# Generated by Django 6.1 on 2026-09-22 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_equipeusf_options_alter_perfilusuario_options_and_more'),
        ('territorializacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaSSA2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('data_preenchimento', models.DateTimeField(auto_now=True)),
                ('gest_cadastradas', models.IntegerField(blank=True, null=True)),
                ('gest_acompanhadas', models.IntegerField(blank=True, null=True)),
                ('gest_vacina_em_dia', models.IntegerField(blank=True, null=True)),
                ('gest_consulta_mes', models.IntegerField(blank=True, null=True)),
                ('gest_inicio_1_trimestre', models.IntegerField(blank=True, null=True)),
                ('gest_menor_20_anos', models.IntegerField(blank=True, null=True)),
                ('total_familias_cadastradas', models.IntegerField(blank=True, null=True)),
                ('visita_domiciliar_acs', models.IntegerField(blank=True, null=True)),
                ('diab_cadastrados', models.IntegerField(blank=True, null=True)),
                ('diab_acompanhados', models.IntegerField(blank=True, null=True)),
                ('hiper_cadastrados', models.IntegerField(blank=True, null=True)),
                ('hiper_acompanhados', models.IntegerField(blank=True, null=True)),
                ('tb_cadastrados', models.IntegerField(blank=True, null=True)),
                ('tb_acompanhados', models.IntegerField(blank=True, null=True)),
                ('han_cadastrados', models.IntegerField(blank=True, null=True)),
                ('han_acompanhados', models.IntegerField(blank=True, null=True)),
                ('hosp_menor_5a_pneumonia', models.IntegerField(blank=True, null=True)),
                ('hosp_menor_5a_desidratacao', models.IntegerField(blank=True, null=True)),
                ('hosp_abuso_alcool', models.IntegerField(blank=True, null=True)),
                ('hosp_complicacao_diabetes', models.IntegerField(blank=True, null=True)),
                ('hosp_outras_causas', models.IntegerField(blank=True, null=True)),
                ('hosp_total', models.IntegerField(blank=True, null=True)),
                ('hosp_psiquiatrico', models.IntegerField(blank=True, null=True)),
                ('nascidos_vivos_mes', models.IntegerField(blank=True, null=True)),
                ('rn_pesados_ao_nascer', models.IntegerField(blank=True, null=True)),
                ('rn_baixo_peso', models.IntegerField(blank=True, null=True)),
                ('cria_0_3m_aleitamento_exclusivo', models.IntegerField(blank=True, null=True)),
                ('cria_0_3m_aleitamento_misto', models.IntegerField(blank=True, null=True)),
                ('cria_0_11m_total', models.IntegerField(blank=True, null=True)),
                ('cria_0_11m_vacina_em_dia', models.IntegerField(blank=True, null=True)),
                ('cria_0_11m_pesadas', models.IntegerField(blank=True, null=True)),
                ('cria_0_11m_desnutridas', models.IntegerField(blank=True, null=True)),
                ('cria_12_23m_total', models.IntegerField(blank=True, null=True)),
                ('cria_12_23m_vacina_em_dia', models.IntegerField(blank=True, null=True)),
                ('cria_12_23m_pesadas', models.IntegerField(blank=True, null=True)),
                ('cria_12_23m_desnutridas', models.IntegerField(blank=True, null=True)),
                ('cria_menor_2a_total', models.IntegerField(blank=True, null=True)),
                ('cria_menor_2a_diarreia', models.IntegerField(blank=True, null=True)),
                ('cria_menor_2a_diarreia_tro', models.IntegerField(blank=True, null=True)),
                ('cria_menor_2a_ira', models.IntegerField(blank=True, null=True)),
                ('obito_menor_28d_diarreia', models.IntegerField(blank=True, null=True)),
                ('obito_menor_28d_ira', models.IntegerField(blank=True, null=True)),
                ('obito_menor_28d_outras', models.IntegerField(blank=True, null=True)),
                ('obito_28d_11m_diarreia', models.IntegerField(blank=True, null=True)),
                ('obito_28d_11m_ira', models.IntegerField(blank=True, null=True)),
                ('obito_28d_11m_outras', models.IntegerField(blank=True, null=True)),
                ('obito_menor_1a_diarreia', models.IntegerField(blank=True, null=True)),
                ('obito_menor_1a_ira', models.IntegerField(blank=True, null=True)),
                ('obito_menor_1a_outras', models.IntegerField(blank=True, null=True)),
                ('obito_mulher_10_14a', models.IntegerField(blank=True, null=True)),
                ('obito_mulher_15_49a', models.IntegerField(blank=True, null=True)),
                ('obito_outras_causas', models.IntegerField(blank=True, null=True)),
                ('obito_total', models.IntegerField(blank=True, null=True)),
                ('obito_adolescente_violencia', models.IntegerField(blank=True, null=True)),
                ('microarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_ssa2', to='core.microarea')),
            ],
            options={
                'verbose_name': 'Ficha SSA2',
                'verbose_name_plural': 'Fichas SSA2',
                'unique_together': {('microarea', 'mes', 'ano')},
            },
        ),
    ]
