# Generated by Django 6.1 on 2026-09-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorializacao', '0002_fichassa2'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichassa2',
            name='cria_0_3m_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
