# Generated by Django 6.1 on 2026-08-19 01:58

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[core.validators.validar_cpf], verbose_name='CPF')),
                ('nivel', models.CharField(choices=[('admin', 'Administrador'), ('funcionario', 'Funcionário'), ('usuario', 'Usuário')], default='usuario', max_length=13, verbose_name='Nível de acesso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
