# Generated by Django 6.1 on 2026-08-20 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do cargo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutirao_ativo', models.BooleanField(default=False, help_text='Quando ativado, o módulo de mutirão aparece no menu para todos os usuários. Administradores sempre veem todos os módulos.', verbose_name='Módulo de mutirão ativo')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='TipoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendimento', models.CharField(max_length=100, unique=True, verbose_name='Nome do atendimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Atendimento',
                'verbose_name_plural': 'Tipos de Atendimento',
                'ordering': ['atendimento'],
            },
        ),
        migrations.CreateModel(
            name='USF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da USF')),
                ('cnes', models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='CNES')),
                ('municipio', models.CharField(default='', max_length=100, verbose_name='Município')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Unidade de Saúde da Família (USF)',
                'verbose_name_plural': 'Unidades de Saúde da Família (USFs)',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Profissional', 'verbose_name_plural': 'Perfis de Profissionais'},
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('categoria', models.CharField(choices=[('aviso', 'Aviso'), ('evento', 'Evento'), ('cronograma', 'Cronograma')], default='aviso', max_length=20, verbose_name='Categoria')),
                ('data_validade', models.DateField(verbose_name='Válido até')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'ordering': ['data_validade'],
            },
        ),
    ]
