# Generated by Django 6.1 on 2026-08-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cargo_configuracaosistema_tipoatendimento_usf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviso',
            name='criado_por',
        ),
    ]
