# Generated by Django 6.1 on 2026-08-21 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_aviso_criado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeUSF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, help_text='Desative ao invés de excluir para preservar o histórico.', verbose_name='Vínculo ativo')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='Data de entrada')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de saída')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profissionais', to='core.cargo', verbose_name='Cargo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_usf', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
                ('usf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipe', to='core.usf', verbose_name='USF')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Equipe da USF',
                'ordering': ['usf', 'cargo', 'user__first_name'],
            },
        ),
    ]
