# Generated by Django 6.1 on 2026-08-23 22:11

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_equipeusf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Hipertensão, Diabetes, Gestante, PCD', max_length=100, unique=True, verbose_name='Nome')),
                ('codigo', models.SlugField(help_text='Identificador único sem espaços. Ex: hipertensao, diabetes, gestante, pcd. Usado pela lógica do sistema — não altere depois de criado.', unique=True, verbose_name='Código interno')),
                ('icone', models.CharField(blank=True, help_text='Emoji para exibir na lista. Ex: ❤️ 🩸 🤰 ♿', max_length=10, verbose_name='Ícone')),
                ('afeta_prioridade', models.BooleanField(default=False, help_text='Se marcado, o sistema sugere prioridade preferencial ao cadastrar encaminhamento para este paciente.', verbose_name='Afeta prioridade no encaminhamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Condição de Saúde',
                'verbose_name_plural': 'Condições de Saúde',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MicroArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: 01, 02, 05A', max_length=10, verbose_name='Código')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('responsavel', models.ForeignKey(blank=True, help_text='Profissional responsável por esta área.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='microareas_responsavel', to='core.equipeusf', verbose_name='Responsável (ACS/TACS)')),
                ('usf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='microareas', to='core.usf', verbose_name='USF')),
            ],
            options={
                'verbose_name': 'Micro-área',
                'verbose_name_plural': 'Micro-áreas',
                'ordering': ['usf', 'codigo'],
                'unique_together': {('usf', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(blank=True, help_text='Somente números, sem pontos ou traços.', max_length=11, null=True, unique=True, validators=[core.validators.validar_cpf], verbose_name='CPF')),
                ('cartao_sus', models.CharField(blank=True, help_text='15 dígitos do Cartão Nacional de Saúde.', max_length=15, null=True, unique=True, verbose_name='Cartão SUS (CNS)')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Não informado')], default='I', max_length=1, verbose_name='Sexo')),
                ('telefone', models.CharField(blank=True, max_length=11, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('obito', models.BooleanField(default=False, help_text='Marque quando o paciente falecer.', verbose_name='Óbito')),
                ('data_obito', models.DateField(blank=True, help_text='Data do falecimento. Preenchimento opcional.', null=True, verbose_name='Data do óbito')),
                ('responsavel_familiar', models.BooleanField(default=False, help_text='Marcado automaticamente pela importação do território.', verbose_name='É responsável familiar')),
                ('cpf_responsavel', models.CharField(blank=True, help_text='CPF de quem é o responsável pela família. Para o próprio responsável, igual ao seu CPF.', max_length=11, verbose_name='CPF do responsável familiar')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('atualizado', models.BooleanField(default=True, help_text='Marcado como False antes de cada importação. Se continuar False após a carga, o paciente não veio no arquivo e será movido para fora de área.', verbose_name='Atualizado na última carga')),
                ('ultima_atualizacao', models.DateTimeField(blank=True, help_text='Data e hora da última importação que atualizou este paciente.', null=True, verbose_name='Última atualização')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
                ('micro_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='core.microarea', verbose_name='Micro-área')),
                ('usf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='core.usf', verbose_name='USF')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PacienteCondicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Quando a condição foi identificada.', verbose_name='Data de início')),
                ('data_referencia', models.DateField(blank=True, help_text='Data relevante para a condição. Para gestante: data prevista do parto. Para outras condições: pode ficar em branco.', null=True, verbose_name='Data de referência')),
                ('data_fim', models.DateField(blank=True, help_text='Quando a condição foi resolvida. Deixe em branco se ainda está ativa.', null=True, verbose_name='Data de encerramento')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('condicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='core.condicaosaude', verbose_name='Condição')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicoes', to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Condição do Paciente',
                'verbose_name_plural': 'Condições do Paciente',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.CheckConstraint(condition=models.Q(('cpf__isnull', False), ('cartao_sus__isnull', False), _connector='OR'), name='paciente_deve_ter_cpf_ou_cns'),
        ),
        migrations.AddConstraint(
            model_name='pacientecondicao',
            constraint=models.UniqueConstraint(condition=models.Q(('data_fim__isnull', True)), fields=('paciente', 'condicao'), name='condicao_ativa_unica_por_paciente'),
        ),
    ]
