# Generated by Django 6.1 on 2026-08-23 23:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_condicaosaude_microarea_paciente_pacientecondicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cadastrado_em',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data do cadastro original na USF. Permite retroceder no tempo.', verbose_name='Cadastrado na unidade em'),
        ),
    ]
