# Generated by Django 6.1 on 2026-09-14 23:19

import core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_paciente_cadastrado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Módulo (Visível no Menu)')),
                ('slug_app', models.CharField(help_text='Ex exatamente como no código: encaminhamentos, mutirao, vacinas', max_length=50, unique=True, verbose_name='Nome Interno (App)')),
                ('ativo', models.BooleanField(default=False, verbose_name='Módulo Ativo')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Módulo do Sistema',
                'verbose_name_plural': 'Módulos do Sistema',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracaoSistema',
        ),
        migrations.AlterField(
            model_name='condicaosaude',
            name='afeta_prioridade',
            field=models.BooleanField(default=False, verbose_name='Afeta prioridade no encaminhamento'),
        ),
        migrations.AlterField(
            model_name='condicaosaude',
            name='codigo',
            field=models.SlugField(unique=True, verbose_name='Código interno'),
        ),
        migrations.AlterField(
            model_name='condicaosaude',
            name='icone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='condicaosaude',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='atualizado',
            field=models.BooleanField(default=True, verbose_name='Atualizado na última carga'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cadastrado_em',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Cadastrado na unidade em'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cartao_sus',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Cartão SUS (CNS)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[core.validators.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=11, verbose_name='CPF do responsável familiar'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_obito',
            field=models.DateField(blank=True, null=True, verbose_name='Data do óbito'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obito',
            field=models.BooleanField(default=False, verbose_name='Óbito'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='responsavel_familiar',
            field=models.BooleanField(default=False, verbose_name='É responsável familiar'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ultima_atualizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última atualização'),
        ),
        migrations.AlterField(
            model_name='pacientecondicao',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de encerramento'),
        ),
        migrations.AlterField(
            model_name='pacientecondicao',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='pacientecondicao',
            name='data_referencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data de referência'),
        ),
    ]
