# Generated by Django 6.1 on 2026-09-15 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_modulosistema_delete_configuracaosistema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao', models.CharField(max_length=150, verbose_name='Condição/Doença')),
                ('grau_parentesco', models.CharField(choices=[('pai_mae', 'Pai / Mãe'), ('avo', 'Avô / Avó'), ('irmao', 'Irmão / Irmã'), ('outro', 'Outro')], max_length=20, verbose_name='Grau de Parentesco')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_familiar', to='core.paciente')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico Familiar',
                'verbose_name_plural': 'Históricos Familiares',
            },
        ),
    ]
