# Generated by Django 6.1 on 2026-09-17 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_historicofamiliar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipeusf',
            options={'verbose_name': 'Vínculo na USF', 'verbose_name_plural': 'Equipa das USFs'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil do Utilizador', 'verbose_name_plural': 'Perfis dos Utilizadores'},
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='nivel',
        ),
        migrations.AddField(
            model_name='equipeusf',
            name='is_admin_unidade',
            field=models.BooleanField(default=False, help_text='Pode gerir a equipa apenas nesta USF.', verbose_name='Administrador desta Unidade'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='is_master',
            field=models.BooleanField(default=False, help_text='Tem acesso a todas as USFs e configurações globais.', verbose_name='Gestor Municipal (Master)'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='usf_ativa_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_logados', to='core.usf'),
        ),
        migrations.AlterField(
            model_name='equipeusf',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Vínculo Ativo'),
        ),
        migrations.AlterField(
            model_name='equipeusf',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='equipeusf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_equipe', to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='equipeusf',
            name='usf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='core.usf', verbose_name='USF'),
        ),
        migrations.AlterUniqueTogether(
            name='equipeusf',
            unique_together={('user', 'usf')},
        ),
    ]
