# Generated by Django 6.1 on 2026-09-14 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_paciente_cadastrado_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Subcategoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao', models.CharField(max_length=150, verbose_name='Condição/Doença')),
                ('grau_parentesco', models.CharField(choices=[('pai_mae', 'Pai / Mãe'), ('avo', 'Avô / Avó'), ('irmao', 'Irmão / Irmã'), ('outro', 'Outro')], max_length=20, verbose_name='Grau de Parentesco')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_familiar', to='core.paciente')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico Familiar',
                'verbose_name_plural': 'Históricos Familiares',
            },
        ),
        migrations.CreateModel(
            name='TipoEncaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Especialidade/Procedimento')),
                ('cota_padrao', models.PositiveIntegerField(default=0, help_text='Quantas vagas a unidade recebe por mês para este procedimento.', verbose_name='Cota Mensal Padrão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos', to='encaminhamentos.subcategoria')),
            ],
            options={
                'verbose_name': 'Tipo de Encaminhamento',
                'verbose_name_plural': 'Tipos de Encaminhamento',
                'ordering': ['subcategoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Vaga'), ('regulacao', 'Em Regulação Municipal'), ('disponivel', 'Disponível para Entrega'), ('entregue', 'Entregue ao Paciente (Concluído)'), ('upae', 'Aguardando UPAE'), ('unificada', 'Fila Unificada (Concluído)'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20, verbose_name='Status')),
                ('prioridade', models.IntegerField(default=1, verbose_name='Nível de Prioridade')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo Clínico/Justificativa')),
                ('mes_retorno', models.IntegerField(blank=True, null=True, verbose_name='Mês de Retorno (Previsão)')),
                ('ano_retorno', models.IntegerField(blank=True, null=True, verbose_name='Ano de Retorno')),
                ('duplicata_de', models.ForeignKey(blank=True, help_text='Se for um encaminhamento repetido, aponte aqui o original.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='encaminhamentos.encaminhamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaminhamentos', to='core.paciente')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Digitado por')),
                ('usf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos', to='core.usf')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos', to='encaminhamentos.tipoencaminhamento')),
            ],
            options={
                'verbose_name': 'Encaminhamento',
                'verbose_name_plural': 'Encaminhamentos',
                'ordering': ['-prioridade', 'data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='RegraCondicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fura_fila', models.BooleanField(default=False, help_text='Passa automaticamente para o topo da fila.', verbose_name='Prioridade Máxima')),
                ('isento_cota', models.BooleanField(default=False, help_text='Não desconta da cota mensal da unidade (Ex: Gestante não gasta cota de USG).', verbose_name='Isento de Cota')),
                ('condicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_encaminhamento', to='core.condicaosaude')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='encaminhamentos.tipoencaminhamento')),
            ],
            options={
                'verbose_name': 'Regra Especial por Condição',
                'verbose_name_plural': 'Regras Especiais por Condição',
                'unique_together': {('tipo', 'condicao')},
            },
        ),
        migrations.CreateModel(
            name='ConfigCota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Específica da USF')),
                ('usf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotas_extras', to='core.usf')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_cotas', to='encaminhamentos.tipoencaminhamento')),
            ],
            options={
                'verbose_name': 'Configuração de Cota por USF',
                'verbose_name_plural': 'Configurações de Cotas por USF',
                'unique_together': {('usf', 'tipo')},
            },
        ),
    ]
