# Generated by Django 6.1 on 2026-09-15 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_modulosistema_delete_configuracaosistema_and_more'),
        ('encaminhamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='cota_padrao',
            field=models.PositiveIntegerField(default=0, help_text='Créditos que a unidade recebe para gastar livremente com qualquer exame/consulta deste grupo.', verbose_name='Cota Mensal Padrão (Compartilhada)'),
        ),
        migrations.CreateModel(
            name='ConfigCotaSubcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Específica da USF')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_cotas', to='encaminhamentos.subcategoria')),
                ('usf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotas_subcategorias', to='core.usf')),
            ],
            options={
                'verbose_name': 'Configuração de Cota da Subcategoria por USF',
                'verbose_name_plural': 'Configurações de Cotas de Subcategoria por USF',
                'unique_together': {('usf', 'subcategoria')},
            },
        ),
    ]
