# Generated by Django 6.1 on 2026-09-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0002_subcategoria_cota_padrao_configcotasubcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoencaminhamento',
            name='idade_maxima',
            field=models.PositiveIntegerField(blank=True, help_text='Ex: 14 para Pediatria. Deixe em branco se não houver limite.', null=True, verbose_name='Idade Máxima (Anos)'),
        ),
        migrations.AddField(
            model_name='tipoencaminhamento',
            name='idade_minima',
            field=models.PositiveIntegerField(blank=True, help_text='Ex: 60 para Geriatria. Deixe em branco se não houver limite.', null=True, verbose_name='Idade Mínima (Anos)'),
        ),
    ]
