# Generated by Django 6.1 on 2026-09-15 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0003_tipoencaminhamento_idade_maxima_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoFamiliar',
        ),
    ]
