# Generated by Django 6.1 on 2026-09-17 02:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0004_delete_historicofamiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='data_status_atual',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrada no Status Atual'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observações da Guia'),
        ),
        migrations.AlterField(
            model_name='encaminhamento',
            name='data_solicitacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Solicitação Original'),
        ),
    ]
