# Generated by Django 6.1 on 2026-09-17 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaminhamentos', '0005_encaminhamento_data_status_atual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEncaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Vaga'), ('regulacao', 'Em Regulação Municipal'), ('disponivel', 'Disponível para Entrega'), ('entregue', 'Entregue ao Paciente (Concluído)'), ('upae', 'Aguardando UPAE'), ('unificada', 'Fila Unificada (Concluído)'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Status na época')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação Registada')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora da Mudança')),
                ('encaminhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='encaminhamentos.encaminhamento')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Histórico do Encaminhamento',
                'verbose_name_plural': 'Históricos dos Encaminhamentos',
                'ordering': ['-data_registro'],
            },
        ),
    ]
