# Generated by Django 6.1 on 2026-09-26 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_equipeusf_options_alter_perfilusuario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Losartana Potássica', max_length=150)),
                ('concentracao', models.CharField(help_text='Ex: 50mg, 500mg/ml', max_length=100)),
                ('forma_farmaceutica', models.CharField(choices=[('COMP', 'Comprimido / Drágea'), ('CAPS', 'Cápsula'), ('GOTA', 'Gotas / Solução Oral'), ('XARO', 'Xarope'), ('INJE', 'Injetável (Ampola)'), ('POMA', 'Pomada / Creme'), ('OUTR', 'Outros')], default='COMP', max_length=4)),
                ('exige_receita_branca', models.BooleanField(default=False, verbose_name='Exige Receita Branca (Controle Simples)')),
                ('exige_receita_controlada', models.BooleanField(default=False, verbose_name='Exige Receita Azul/Amarela (Psicotrópicos)')),
                ('antibiotico', models.BooleanField(default=False, verbose_name='Antibiótico (Retenção de Receita)')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Dispensacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dispensacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_recebidos', to='core.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensacoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensacoes', to='core.usf')),
            ],
            options={
                'verbose_name': 'Dispensação',
                'verbose_name_plural': 'Dispensações',
                'ordering': ['-data_dispensacao'],
            },
        ),
        migrations.CreateModel(
            name='LoteEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(blank=True, max_length=50, null=True)),
                ('data_validade', models.DateField()),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques_farmacia', to='core.usf')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='farmacia.medicamento')),
            ],
            options={
                'verbose_name': 'Lote de Estoque',
                'verbose_name_plural': 'Lotes de Estoque',
                'ordering': ['data_validade'],
            },
        ),
        migrations.CreateModel(
            name='ItemDispensacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_entregue', models.PositiveIntegerField()),
                ('posologia_diaria', models.DecimalField(decimal_places=2, help_text='Quantos comprimidos toma por dia?', max_digits=5)),
                ('dias_tratamento', models.PositiveIntegerField(help_text='Para quantos dias dá este remédio?')),
                ('data_proxima_retirada', models.DateField(help_text='Quando o paciente pode voltar para pegar mais?')),
                ('dispensacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='farmacia.dispensacao')),
                ('lote_utilizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.loteestoque')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.medicamento')),
            ],
        ),
    ]
