# Generated by Django 6.1 on 2026-09-26 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdispensacao',
            name='justificativa_antecipacao',
            field=models.CharField(blank=True, help_text='Ex: Alteração de posologia médica, Perda/Roubo, etc.', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('ENTRADA_CAF', '📥 Entrada (Recebimento da CAF Central)'), ('ENTRADA_TRANSFERENCIA', '📥 Entrada por Transferência (De outra USF)'), ('ENTRADA_AJUSTE', '📥 Entrada (Ajuste de inventário)'), ('SAIDA_TRANSFERENCIA', '📤 Saída por Transferência (Para outra USF)'), ('SAIDA_PERDA', '📤 Saída por Perda / Vencimento / Avaria'), ('SAIDA_AJUSTE', '📤 Saída (Ajuste de inventário)')], max_length=25)),
                ('quantidade', models.PositiveIntegerField(help_text='Sempre positivo. O sistema soma ou subtrai automaticamente.')),
                ('data_movimento', models.DateTimeField(auto_now_add=True)),
                ('justificativa', models.CharField(blank=True, help_text='Ex: Transferido para USF Centro. Venceu na prateleira.', max_length=255, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='farmacia.loteestoque')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimento'],
            },
        ),
    ]
