# Generated by Django 6.1 on 2026-09-26 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_equipeusf_options_alter_perfilusuario_options_and_more'),
        ('farmacia', '0002_itemdispensacao_justificativa_antecipacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteestoque',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='loteestoque',
            name='registrado_por',
        ),
        migrations.AlterField(
            model_name='itemdispensacao',
            name='posologia_diaria',
            field=models.DecimalField(decimal_places=2, help_text='Quantos toma por dia?', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loteestoque',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loteestoque',
            name='numero_lote',
            field=models.CharField(blank=True, help_text='Deixe em branco se a USF não controlar o lote exato.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loteestoque',
            name='quantidade_atual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loteestoque',
            name='usf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_farmacia', to='core.usf'),
        ),
    ]
