# Generated by Django 6.1 on 2026-09-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0003_remove_loteestoque_data_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdispensacao',
            name='uso_continuo',
            field=models.BooleanField(default=False, help_text='Marque se o paciente vai precisar retirar este item todos os meses.', verbose_name='Uso Contínuo / Repetição'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='tipo',
            field=models.CharField(choices=[('MED', 'Medicamento'), ('INS', 'Insumo / Material Técnico')], default='MED', max_length=3, verbose_name='Tipo de Item'),
        ),
        migrations.AlterField(
            model_name='itemdispensacao',
            name='data_proxima_retirada',
            field=models.DateField(blank=True, help_text='Quando o paciente pode voltar para pegar mais?', null=True),
        ),
        migrations.AlterField(
            model_name='itemdispensacao',
            name='dias_tratamento',
            field=models.PositiveIntegerField(blank=True, help_text='Para quantos dias dá? (Deixe em branco para insumos)', null=True),
        ),
        migrations.AlterField(
            model_name='itemdispensacao',
            name='posologia_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantos toma por dia? (Deixe em branco para insumos)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='concentracao',
            field=models.CharField(blank=True, help_text='Ex: 50mg. Deixe em branco para insumos (ex: 10x10cm).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='forma_farmaceutica',
            field=models.CharField(choices=[('COMP', 'Comprimido / Drágea'), ('CAPS', 'Cápsula'), ('GOTA', 'Gotas / Solução Oral'), ('XARO', 'Xarope'), ('INJE', 'Injetável (Ampola)'), ('POMA', 'Pomada / Creme'), ('PACO', 'Pacote'), ('ROLO', 'Rolo / Bobina'), ('UNID', 'Unidade Avulsa'), ('CX', 'Caixa'), ('OUTR', 'Outros')], default='COMP', max_length=4),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(help_text='Ex: Losartana Potássica ou Atadura de Crepe', max_length=150),
        ),
    ]
