# Generated by Django 6.1 on 2026-09-26 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_equipeusf_options_alter_perfilusuario_options_and_more'),
        ('farmacia', '0004_itemdispensacao_uso_continuo_medicamento_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaReprimida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_em_falta', to='core.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('usf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas_reprimidas', to='core.usf')),
            ],
            options={
                'verbose_name': 'Demanda Reprimida (Falta)',
                'verbose_name_plural': 'Demandas Reprimidas (Faltas)',
                'ordering': ['-data_registro'],
            },
        ),
    ]
