# Generated by Django 6.1 on 2026-09-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_demandareprimida'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='codigo_br',
            field=models.CharField(blank=True, help_text='Código oficial do produto (Ex: BR0272906)', max_length=50, null=True, verbose_name='Código BR / CATMAT'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='concentracao',
            field=models.CharField(blank=True, help_text='Ex: 500mg, 50mg/ml (Deixe em branco para Insumos)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='tipo',
            field=models.CharField(choices=[('MED', 'Medicamento'), ('INS', 'Insumo / Material Técnico')], default='MED', max_length=3),
        ),
    ]
