# Generated by Django 6.1 on 2026-09-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0006_medicamento_codigo_br_alter_medicamento_concentracao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={},
        ),
    ]
