# Generated by Django 6.1 on 2026-09-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0007_alter_medicamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={'ordering': ['nome'], 'verbose_name': 'Item do Catálogo (REMUME)', 'verbose_name_plural': 'Catálogo de Medicamentos e Insumos'},
        ),
    ]
