# Generated by Django 6.1 on 2026-09-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0008_alter_medicamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
