# Generated by Django 6.1 on 2026-09-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0009_alter_medicamento_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='forma_farmaceutica',
            field=models.CharField(blank=True, choices=[('COMP', 'Comprimido / Drágea'), ('CAPS', 'Cápsula'), ('GOTA', 'Gotas / Solução Oral'), ('XARO', 'Xarope'), ('INJE', 'Injetável (Ampola)'), ('POMA', 'Pomada / Creme'), ('PACO', 'Pacote'), ('ROLO', 'Rolo / Bobina'), ('UNID', 'Unidade Avulsa'), ('CX', 'Caixa'), ('OUTR', 'Outros')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('MED', 'Medicamento'), ('INS', 'Insumo / Material Técnico')], max_length=3, null=True),
        ),
    ]
